### ISSUE TITLE
Release 0.12.0

### ISSUE THREAD

**Issue by edemaine** [KaTeX/KaTeX#2287]
@ronkok [here](https://github.com/KaTeX/KaTeX/issues/2286#issuecomment-655681853):
> ... #2219, which was fixed by PR #2220 in March. The problem is that we have not had a release issued since September. There are also some bug fix PRs waiting for review, much less release.

We should review at least the bug-fix PRs, and then do a release.  (Sorry, I've been slacking on this as much as everyone.)  @ronkok, can you list which PRs you think are important and/or easy for review before release, so we can prioritize?  I'll then make a list here that can track progress:

Bug fixes:

* [x] PR #2234, Fix a parenthesis rendering bug &mdash; awaiting responses/revisions
* [x] PR #2278, Prevent a crash when `\substack` has no argument.
* [x] PR #1841, Remove space after `\\`
* [x] PR #2290, Fix `\boldsymbol{\Omega}`
* [x] PR #2236, Fix fraction bar color
* [x] PR #2295, Fix website `trust`
* [x] PR #2156, Font cleanup, fix `\i` spacing

PRs that aim at making the documentation more clear or complete:
* [x] PR #2269
* [x] PR #2279
* [x] PR #2280 &mdash; ~~blocked on https://github.com/bradhowes/remarkable-katex/issues/4~~
* [x] PR #2289
* [x] PR #2297

**Comment by ronkok** [comment]
Bug fixes:

* PR #2234, Fix a parenthesis rendering bug.
* PR #2278, Prevent a crash when `\substack` has no argument.

Others have contributed PRs that aim at making the documentation more clear or complete:
 * PR #2269
* PR #2279
* PR #2280

There are also some cool feature enhancements, but we should not wait for their review. We ought to get a release out right away.

**Comment by jxxcarlson** [comment]
re the comment on incorrect rendering via a custom element in #2286:

re the below, unfortunately not the case.  If I remove `output: mathml` from options in `elm-katex.js`, the output is as in the attached image, which is why I had put that option in the code.

> I believe this is an issue with MathML, not KaTeX. (But @ronkok can correct me on that.) If you take out the output: 'mathml', and let KaTeX do its thing (use both HTML and MathML output), you'll probably get better results.

<img width="373" alt="Screen Shot 2020-07-08 at 9 57 26 PM" src="https://user-images.githubusercontent.com/679991/86964510-790de480-c166-11ea-9152-5b0b40b494c5.png">

Is this something for which there will be a solution in the relatively near future?

Thanks!

**Comment by ylemkimon** [comment]
If possible, it'd be best get either #2156 or #2134 merged, but as it has been a long time since the last release, I don't mind including them in the next release.

**Comment by edemaine** [comment]
It'd be nice to get your nice PRs #2134, #2131, #2085 merged, but that is probably a larger effort. I'm imagining 0.12.0 would be good to just get the various improvements over the last six months, but as #2134 is a breaking change, maybe someone would want those improvements (including bug fixes) without having to adjust their code to avoid relying on greediness. (I'm wondering whether it would be better to do a deprecation warning in a release beforehand...? Or keeping greediness, but with a nonstrict warning? Anyway, would kinda like to push this off...)

#2156 would be nice to merge (hence my partial review). Let's see if we can get that one in.

@ylemkimon When the time comes (hopefully soon), do you want to do the release process or should I? You've done it more recently, so it might be easier for you (happy to review the resulting PR), but I'm also willing to do it.

**Comment by ylemkimon** [comment]
I can do it. But another concern is #2082, which may cause security issues. I think its documentation is insufficient.

**Comment by edemaine** [comment]
@ylemkimon Could you elaborate on the lack of documentation? I looked at https://katex.org/docs/next/supported.html#html and the `strict` documentation in https://katex.org/docs/next/options.html and it seemed OK in terms of security. We just need to be careful in the release notes to point out that there's new security options, so `security: true` has a different meaning now than before.

Perhaps the rendered form in https://katex.org/docs/next/supported.html#html would be clearer if we also included the raw HTML repeated like `...<span class="enclosing" data-foo="a" data-bar="b">...x...</span>...`?

**Comment by ylemkimon** [comment]
@edemaine I don't have any specific thoughts, but for instance, https://github.com/KaTeX/KaTeX/pull/2296/files#r453218268. I think we should explicitly state there exists commands that loads external resources or change HTML attributes.

**Comment by edemaine** [comment]
Perhaps we've reached a good time to do a release? Or did you want to finish #2301 first?

**Comment by ylemkimon** [comment]
@edemaine I think it'd be safe to do with the current environment. I'll prepare a release PR.
